# Generated by Django 5.2 on 2025-05-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_initiated",
                        to="pets.pet",
                    ),
                ),
                (
                    "to_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_received",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_pet", "to_pet")},
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="friends",
            field=models.ManyToManyField(
                related_name="friend_of", through="pets.Friendship", to="pets.pet"
            ),
        ),
    ]
